use super::ai::RustyCrabPlanetAI;
use common_game::components::planet::{Planet, PlanetType};
use common_game::components::resource::BasicResourceType;
use common_game::components::resource::ComplexResourceType::{
    AIPartner, Diamond, Dolphin, Life, Robot, Water,
};
use common_game::protocols::{orchestrator_planet, planet_explorer};

/// Function to create and initialize the `RustyCrab` planet instance.
/// It allows to pass a basic resource that will be generated by the planet. (this feature is deprecated)
///
/// # Example
/// ```rust,ignore
/// let mut planet = create_planet(
///     rx_from_orch,
///     tx_from_planet_orch,
///     rx_from_expl,
///     0u32);
/// ```
///
/// # Panics
/// Panics if the planet creation fails. This should not happen when using the common crate.
#[must_use]
pub fn create_planet(
    rx_orchestrator: crossbeam_channel::Receiver<orchestrator_planet::OrchestratorToPlanet>,
    tx_orchestrator: crossbeam_channel::Sender<orchestrator_planet::PlanetToOrchestrator>,
    rx_explorer: crossbeam_channel::Receiver<planet_explorer::ExplorerToPlanet>,
    planet_id: u32,
) -> Planet {
    let ai = RustyCrabPlanetAI {};
    let gen_rules = vec![BasicResourceType::Hydrogen];
    let comb_rules = vec![Diamond, Water, Life, Robot, Dolphin, AIPartner];

    // Construct the planet and return it
    Planet::new(
        planet_id,
        PlanetType::C,
        Box::new(ai),
        gen_rules,
        comb_rules,
        (rx_orchestrator, tx_orchestrator),
        rx_explorer,
    )
    .expect("Failed to create the planet")
}
